apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anchore-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: anchore-sc
  volumeMode: Filesystem