apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-{{ .Values.pipeline.sequence }}
  annotations:
    {{- include "iiidevops.annotations" . | nindent 4 }}
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-{{ .Values.pipeline.sequence }}
      annotations:
        {{- include "iiidevops.annotations" . | nindent 8 }}
    spec:
      containers:
        - name: anchore-scan-{{ include "numericSafe" .Values.git.commitID }}-{{ .Values.pipeline.sequence }}
          image: {{ .Values.harbor.host }}/{{ .Values.image.repository }}:{{ .Values.anchore.runnerVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['/startup.sh','{{ .Values.harbor.host }}/{{ .Values.anchore.image }}']
          volumeMounts:
            - mountPath: "/grype-db"
              name: anchore-data
          env:
            - name: git_url
              value: {{ .Values.git.url }}
            - name: git_branch
              value: {{ include "numericSafe" .Values.git.branch | quote }}
            - name: git_commit_id
              value: {{ include "numericSafe" .Values.git.commitID | quote }}
            - name: api_origin
              valueFrom:
                secretKeyRef:
                  name: nexus
                  key: api-origin
            # username of the API server
            - name: api_username
              valueFrom:
                secretKeyRef:
                  name: nexus-bot
                  key: username
            # password of the API server
            - name: api_password
              valueFrom:
                secretKeyRef:
                  name: nexus-bot
                  key: password
      restartPolicy: Never
      volumes:
      - name: anchore-data
        persistentVolumeClaim:
          claimName: anchore-pvc
  backoffLimit: 1