apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web.name" . }}-dpy
  labels:
    {{- include "iiidevops.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "web.name" . }}
      {{- include "iiidevops.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "web.name" . }}
        {{- include "iiidevops.labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- .Values.imagePullSecrets | toYaml | nindent 8 }}
      securityContext:
        {{- .Values.podSecurityContext | toYaml | nindent 8 }}
      containers:
        - name: "web-server-{{ include "numericSafe" .Values.git.commitID }}"
          securityContext:
            {{- .Values.securityContext | toYaml | nindent 12 }}
          image: "{{ .Values.harbor.host }}/{{ .Values.web.imageTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: repo_name
              value: {{ .Values.git.repoName }}
            - name: git_branch
              value: {{ include "numericSafe" .Values.git.branch }}
            - name: git_commit_id
              value: {{ include "numericSafe" .Values.git.commitID | quote }}
            - name: db_host
              value: {{ .Release.Name }}-svc
            - name: db_name
              value: {{ .Values.db.name }}
            - name: db_username
              value: {{ .Values.db.username }}
            - name: db_password
              value: {{ .Values.db.password }}
          ports:
            - containerPort: {{ .Values.web.port }}
              protocol: TCP
          resources:
            {{- .Values.resources | toYaml | nindent 12 }}
      nodeSelector:
        {{- .Values.nodeSelector | toYaml | nindent 8 }}
      affinity:
        {{- .Values.affinity | toYaml | nindent 8 }}
      tolerations:
        {{- .Values.tolerations | toYaml | nindent 8 }}
