apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-{{ .Values.pipeline.sequence }}
  annotations:
    {{- include "iiidevops.annotations" . | nindent 4 }}
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-{{ .Values.pipeline.sequence }}
      annotations:
        {{- include "iiidevops.annotations" . | nindent 8 }}
    spec:
      containers:
        - name: cmas-scan-{{ include "numericSafe" .Values.git.commitID }}-{{ .Values.pipeline.sequence }}
          image: iiiorg/cmas-runner:{{ .Values.cmas.runnerVersion }}
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'cd /cmas; python3 main.py;']
          env:
            - name: cm_url
              value: {{ .Values.cmas.url }}
            - name: authKey
              value: {{ .Values.cmas.key }}
            - name: a_mode
              value: {{ .Values.cmas.a_mode }}
            - name: a_report_type
              value: {{ .Values.cmas.a_report_type }}
            - name: a_ert
              value: {{ .Values.cmas.a_ert }}
            - name: git_url
              value: {{ .Values.git.url }}
            - name: git_branch
              value: {{ include "numericSafe" .Values.git.branch | quote }}
            - name: git_commit_id
              value: {{ include "numericSafe" .Values.git.commitID | quote }}
            - name: api_origin
              value: {{ .Values.api.url }}
            - name: api_username
              value: {{ .Values.api.username }}
            - name: api_password
              value: {{ .Values.api.password }}
          volumeMounts:
            - mountPath: /usr/src/app/repo
              name: initrepo
      initContainers:
        - name: clone-repo-{{ .Values.git.repoName }}-{{ include "numericSafe" .Values.git.branch }}-{{ include "numericSafe" .Values.git.commitID }}-{{ .Values.pipeline.sequence }}
          image: alpine/git
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
          args:
            - >-
              cd /init-data;
              export se="//";
              export url="${git_url/$se*/$se}${git_username}:${git_token}@${git_url/*$se}";
              git clone --branch ${git_branch} ${url} .;
              rm -rf .git;
              chmod -R 777 .;
          env:
            - name: git_url
              value: {{ .Values.git.url }}
            - name: git_branch
              value: {{ include "numericSafe" .Values.git.branch | quote }}
            - name: git_token
              valueFrom:
                secretKeyRef:
                  name: gitlab-bot
                  key: git-token
            # nexus username = gitlab username of BOT to clone
            - name: git_username
              valueFrom:
                secretKeyRef:
                  name: nexus-bot
                  key: username
          volumeMounts:
            - mountPath: /init-data
              name: initrepo
      # 暫時專案資料儲存區
      volumes:
        - name: initrepo
          emptyDir: {}
      restartPolicy: Never
  backoffLimit: 4