apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-{{ .Values.pipeline.sequence }}
  annotations:
    {{- include "iiidevops.annotations" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      name: {{ .Release.Name }}-{{ .Values.pipeline.sequence }}
      annotations:
        {{- include "iiidevops.annotations" . | nindent 8 }}
    spec:
      containers:
        - name: test-sideex-{{ include "numericSafe" .Values.git.commitID }}-{{ .Values.pipeline.sequence }}
          image: iiiorg/sideex-runner:{{ .Values.sideex.runnerVersion }}
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'run.sh']
          env:
            - name: target_origin
              value: http://{{ .Values.web.deployName }}-svc:{{ .Values.web.port }}
            # Project name
            - name: api_origin
              valueFrom:
                secretKeyRef:
                  name: nexus
                  key: api-origin
            - name: username
              valueFrom:
                secretKeyRef:
                  name: nexus-bot
                  key: username
            - name: password
              valueFrom:
                secretKeyRef:
                  name: nexus-bot
                  key: password
            - name: project_name
              value: {{ .Values.git.repoName }}
            # Git info for nexus
            - name: git_branch
              value: {{ include "numericSafe" .Values.git.branch | quote }}
            - name: git_commit_id
              value: {{ include "numericSafe" .Values.git.commitID | quote }}
      restartPolicy: Never
  backoffLimit: 4