- name: Source scan
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:iii-dev-charts3-source-scan
      version: 0.1.0
      name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-source-scan
      targetNamespace: ${CICD_GIT_REPO_NAME}
      answers:
        harbor.host: "harbor71.iiidevops.org"
        # 基礎pipeline參數
        pipeline.sequence: ${CICD_EXECUTION_SEQUENCE}
        git.url: ${CICD_GIT_URL}
        git.branch: ${CICD_GIT_BRANCH}
        git.commitID: ${CICD_GIT_COMMIT}
        git.repoName: ${CICD_GIT_REPO_NAME}
        # web參數設定
        checkmarx.enabled: true
        sonarqube.enabled: true

notification: {}
