git:
  url: "http://gitlab.your.domain/project.git"
  repoName: "project"
  branch: "master"
  commitID: "abc1234"
pipeline:
  sequence: 0
sonarqube:
  runnerVersion: 1.1.0
  env: false
harbor:
  host: "localhost:32443"
image:
  repository: dockerhub/iiiorg/sonarqube-runner
  pullPolicy: IfNotPresent
  pullSecrets: []
timezone:
  tz: Asia/Taipei
  
# 可指定紀錄(資源)的存活時間time to live設計
ttlSecondsAfterFinished: null
type: nomal
gradle:
  image: "dockerhub/iiiorg/sonarqube-runner"
  tag: "gradle-jdk11-1.1.0"
maven:
  image: "dockerhub/iiiorg/sonarqube-runner"
  tag: "maven-3.6.3-openjdk-11-1.1.0" 
asp_dot_net:
  image: "dockerhub/iiiorg/sonarqube-runner"
  tag: "dotnet-sdk-3.1-focal-1.1.0"
