apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
type: Opaque
data:
  postgresql-postgres-password: {{ .Values.db.username | b64enc | quote }}
  postgresql-password: {{ .Values.db.password | b64enc | quote }}