pipeline:
  sequence: 0
harbor:
  host: "harbor.domain"
git:
  url: "http://gitlab.domain/project.git"
  branch: "master"
  commitID: "abc12345"
  repoName: "project-name"
web:
  port: 80
  imageTag: "project/branch:version"
db:
  releaseName: "project-branch-serv"
  username: "bear"
  password: "bearbearbear"
  name: "bearDB"