apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.name" . }}-svc
  labels:
    {{- include "iiidevops.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: {{ include "web.name" . }}
  ports:
      - port: {{ .Values.web.port }}
        protocol: TCP
