apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-{{ .Values.pipeline.sequence }}
  annotations:
    {{- include "iiidevops.annotations" . | nindent 4 }}
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-{{ .Values.pipeline.sequence }}
      annotations:
        {{- include "iiidevops.annotations" . | nindent 8 }}
    spec:
      containers:
        - name: webinspect-runner-{{ .Values.pipeline.sequence }}
          image: {{ .Values.harbor.host }}/{{ .Values.image.repository }}:{{ .Values.webinspect.runnerVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}         
          command: ['sh', '-c', 'cd /usr/src/app; python3 /usr/src/app/main.py;']
          env:
            - name: target_origin
              value: http://{{ .Values.web.deployName }}-svc:{{ .Values.web.port }}
            - name: scan_policy_name
              value: OWASP Top 10 2021
            - name: project_name
              value: {{ .Values.git.repoName }}
            # Indicates the tested branch name
            - name: git_url
              value: {{ .Values.git.url }}
            - name: git_branch
              value: {{ include "numericSafe" .Values.git.branch | quote }}
            # Indicates the tested commit
            - name: git_commit_id
              value: {{ include "numericSafe" .Values.git.commitID | quote }}
            - name: wi_scc_url
              valueFrom:
                secretKeyRef:
                  name: webinspect
                  key: wi_scc_url
            - name: wi_dast_url
              valueFrom:
                secretKeyRef:
                  name: webinspect
                  key: wi_dast_url
            - name: wi_username
              valueFrom:
                secretKeyRef:
                  name: webinspect
                  key: wi-username
            - name: wi_password
              valueFrom:
                secretKeyRef:
                  name: webinspect
                  key: wi-password
            - name: api_origin
              valueFrom:
                secretKeyRef:
                  name: nexus
                  key: api-origin
            - name: api_username
              valueFrom:
                secretKeyRef:
                  name: nexus-bot
                  key: username
            - name: api_password
              valueFrom:
                secretKeyRef:
                  name: nexus-bot
                  key: password
            - name: TZ
              value: {{ .Values.timezone.tz }}
      restartPolicy: Never
  backoffLimit: 2