## 此步驟先偵測資料庫的svc是否正常(init)，然後再將bak的檔案匯入進去
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-import"
  labels:
    {{- include "mssql-server.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: import-dump-db
        image: "mcr.microsoft.com/mssql-tools"
        command: ["/bin/sleep","{{ default "10" .Values.sleepyTime }}"]