apiVersion: v1
kind: Service
metadata:
  name: {{ include "mssql-server.fullname" . }}
  labels:
    {{- include "mssql-server.labels" . | nindent 4 }}
    app: {{ .Release.Name }}
  annotations:
    {{- include "iiidevops.annotations" . | nindent 4 }}
    iiidevops.org/type: db-server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mssql
      protocol: TCP
      name: mssql
  selector:
    {{- include "mssql-server.selectorLabels" . | nindent 4 }}
    app: {{ .Release.Name }}
