apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: {{ .Release.Name }}
  annotations:
    {{- include "iiidevops.annotations" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
  ports:
      - port: {{ .Values.web.port }}
        protocol: TCP
