apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
    {{- include "iiidevops.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  # warning: replicas only support for 1, above it won't support master slave
  # dont use this chart in production env
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
      {{- include "iiidevops.labels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: "{{ .Release.Name }}"
        {{- include "iiidevops.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.db.type }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          #image: "{{ .Values.db.image }}:{{ .Values.db.tag }}"
        {{- if eq .Values.db.type "mysql" }}
          image: "bitnami/mysql:{{ .Values.db.tag }}"
        {{- else if eq .Values.db.type "mariadb" }}
          image: "bitnami/mariadb:{{ .Values.db.tag }}"
        {{- else if eq .Values.db.type "postgresql" }}
          image: "bitnami/postgresql:{{ .Values.db.tag }}"
        {{- else if eq .Values.db.type "mongodb" }}
          image: "bitnami/mongodb:{{ .Values.db.tag }}"
        {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: db
            {{- if eq .Values.db.type "mysql" }}
              containerPort: 3306
            {{- else if eq .Values.db.type "mariadb" }}
              containerPort: 3306
            {{- else if eq .Values.db.type "postgresql" }}
              containerPort: 5432
            {{- else if eq .Values.db.type "mongodb" }}
              containerPort: 27017
            {{- end }}
              protocol: TCP
        {{- if eq .Values.db.type "postgresql" }}  
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U {{ .Values.db.username }} -d "dbname={{ .Values.db.name }}" -h 127.0.0.1 -p 5432
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - -e
                - exec pg_isready -U {{ .Values.db.username }} -d "dbname={{ .Values.db.name }}" -h 127.0.0.1 -p 5432
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
          env:
        {{- if eq .Values.db.type "mysql" }}
          - name: MYSQL_ROOT_USER
            value: {{ .Values.db.username }}
          - name: MYSQL_ROOT_PASSWORD
            value: {{ .Values.db.password }}
          - name: MYSQL_DATABASE
            value: {{ .Values.db.name }}
        {{- else if eq .Values.db.type "mariadb" }}
          - name: MARIADB_ROOT_USER
            value: {{ .Values.db.username }}
          - name: MARIADB_ROOT_PASSWORD
            value: {{ .Values.db.password }}
          - name: MARIADB_DATABASE
            value: {{ .Values.db.name }}
        {{- else if eq .Values.db.type "postgresql" }}
          - name: POSTGRESQL_USERNAME
            value: {{ .Values.db.username }}
          - name: POSTGRESQL_PASSWORD
            value: {{ .Values.db.password }}
          - name: POSTGRESQL_DATABASE
            value: {{ .Values.db.name }}
        {{- else if eq .Values.db.type "mongodb" }}
          - name: MONGODB_ROOT_PASSWORD
            value: {{ .Values.db.rootpassword }}
        {{- end }}
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: initdb
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      # 自動將資料庫所需匯入的表單匯入到資料庫
      initContainers:
        - name: "clone-repo-{{ .Values.git.repoName }}-{{ include "numericSafe" .Values.git.branch }}-{{ include "numericSafe" .Values.git.commitID }}"
          image: "{{ .Values.harbor.host }}/{{ .Values.harbor.cache }}/alpine/git"
          command:
            - /bin/sh
            - -c
          args:
            - >-
              cd /initdb-data;
              export se="//";
              export url="${git_url/$se*/$se}${git_username}:${git_token}@${git_url/*$se}";
              git clone --branch ${git_branch} ${url} .;
              rm -rf .git;
              chmod -R 777 .;
          env:
            - name: git_url
              value: {{ .Values.git.url }}
            - name: git_branch
              value: {{ include "numericSafe" .Values.git.branch | quote }}
            - name: git_token
              valueFrom:
                secretKeyRef:
                  name: gitlab-bot
                  key: git-token
            # nexus username = gitlab username of BOT to clone
            - name: git_username
              valueFrom:
                secretKeyRef:
                  name: nexus-bot
                  key: username
          volumeMounts:
            - mountPath: /initdb-data
              name: initdb
      volumes:
        - name: initdb
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
