apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.git.repoName }}-{{ .Values.git.repoName }}-svc"
  labels:
    {{- include "php.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "php.selectorLabels" . | nindent 4 }}
