apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}svc
  labels:
    {{- include "iiidevops.labels" . | nindent 4 }}
  iiidevops.org/service_type: web-server
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
  ports:
      - port: {{ .Values.web.port }}
        protocol: TCP
