# 線上API編寫的部屬(如果使用者有說明需要API線上部屬服務的話)
{{ if eq .Values.codeServer.enabled true -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-codeserver"
  labels:
    #{{- include "web.labels" . | nindent 4 }}
    app: "{{ .Release.Name }}-codeserver"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      #{{- include "web.selectorLabels" . | nindent 6 }}
      app: "{{ .Release.Name }}-codeserver"
  template:
    metadata:
      labels:
        #{{- include "web.selectorLabels" . | nindent 8 }}
        app: "{{ .Release.Name }}-codeserver"
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: codeserver
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.harbor.host }}/{{ .Values.harbor.cache }}/linuxserver/code-server"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: codeserver
              containerPort: 8443
              protocol: TCP
          env:
            - name: PUID
              value: "{{ .Values.codeServer.PUID }}"
            - name: PGID
              value: "{{ .Values.codeServer.PGID }}"
            - name: TZ
              value: {{ .Values.codeServer.TZ }}
            - name: PASSWORD
              value: {{ .Values.codeServer.PASSWORD }}
            - name: SUDO_PASSWORD
              value: {{ .Values.codeServer.PASSWORD }}
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          # 使用者登入的Workspace空間資料
          volumeMounts:
            - mountPath: /config/workspace
              name: initrepo
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      # 匯入使用者的開發專案程式碼提供其線上進行修改
      initContainers:
        - name: initializing-a-new-instance
          image: "{{ .Values.harbor.host }}/{{ .Values.harbor.cache }}/alpine/git"
          command: ['sh', '-c', 'cd /init-data; git clone --branch ${git_branch} http://root:${git_token}@${git_host}/root/${git_repo}.git .; ls; chmod -R 777 /init-data']
          env:
            - name: git_host
              value: {{ .Values.git.host }}
            - name: git_repo
              value: {{ .Values.git.repoName }}
            - name: git_branch
              value: {{ .Values.git.branch }}
            - name: git_token
              valueFrom:
                secretKeyRef:
                  name: gitlab-token
                  key: git-token
          volumeMounts:
            - mountPath: /init-data
              name: initrepo
      volumes:
        - name: initrepo
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}