{{- if .Values.ingress.enabled -}}
{{- $fullName := include "web.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  #name: {{ $fullName }}
  name: "{{ .Release.Name }}-{{ .Values.web.type }}-ing"
  labels:
    #{{- include "web.labels" . | nindent 4 }}
    app: "{{ .Release.Name }}-{{ .Values.web.type }}"
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
#{{- if .Values.ingress.tls }}
#  tls:
#  {{- range .Values.ingress.tls }}
#    - hosts:
#      {{- range .hosts }}
#        - {{ . | quote }}
#      {{- end }}
#      secretName: {{ .secretName }}
#  {{- end }}
#{{- end }}
  rules:
  - host: "{{ .Values.web.type }}.{{ .Values.git.branch}}.{{ .Values.git.repoName }}.{{ .Values.xip.ip }}.xip.io"
    http:
      paths:
      - backend:
          serviceName: "{{ .Release.Name }}-{{ .Values.web.type }}-svc"
        {{- if eq .Values.web.type "php" }}
          servicePort: 80
        {{- else if eq .Values.web.type "flask" }}
          servicePort: 5000
        {{- else if eq .Values.web.type "uwsgi-flask" }}
          servicePort: 80
        {{- else if eq .Values.web.type "spring" }}
          servicePort: 8080
        {{- else if eq .Values.web.type "custom" }}
          servicePort: {{ .Values.web.port }}
        {{- end }}
        path: "/"
        pathType: "ImplementationSpecific"
{{- end }}
