apiVersion: {{ if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
networking.k8s.io/v1beta1
{{- else -}}
extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "web.fullname" . }}-ingress
  labels:
    {{ include "web.labels" | nindent 4 }}
  annotations:
    {{- .Values.ingress.annotations | toYaml | nindent 4 }}
spec:
  rules:
  - host: "{{ include "web.fullname" }}.{{ .Values.xip.ip }}.xip.io"
    http:
      paths:
      - backend:
          serviceName: "{{ include "web.fullname" . }}-service"
          servicePort: {{ include "web.port" . }}
        path: "/"
        pathType: "ImplementationSpecific"
