harbor:
  host: "localhost:32443"

git:
  repoName: "projectName"
  branch: "branch"
  commitId: "abc12345"
  url: "giturl"
# db可選型態
# "mysql"、"mariadb"、"postgresql"、"mongodb"、"custom"
# web.port 僅 custom時候使用
db:
  enabled: true
  gui: true
  type: "mysql"
  username: "bear"
  password: "bearbearbear"
  name: "bearDB"
  tag: "latest"

replicaCount: 1

service:
  type: NodePort
  port: 80

nodePort:
  enabled: false
  port: 30080

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

## Configure extra options for liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
##
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
    
volumeMounts:
  hostPath:
    enabled: false
    path: '/project-data'
  nfs:
    enabled: false
    server: localhost
    path: '/iiidevopsNFS/devops-data/project-data'
  project : 'default'
  uuid : 'project-uuid'