git:
  url: "http://gitlab.your.domain/project.git"
  repoName: "project"
  branch: "master"
  commitID: "abc1234"
pipeline:
  sequence: 0
cmas:
  a_mode: "24"
  a_ert: "90" 
  runnerVersion: latest
harbor:
  host: harbor-dev3.iiidevops.org
image:
  repository: cmas-runner/master
  pullPolicy: Always
  pullSecrets: []