# 這裡會為本專案產生一組安全很長的密碼
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.git.repoName }}-{{ .Values.git.branch }}-{{ .Release.Name }}-secret"
stringData:
  dbusername: root
  dbpassword: {{ .Values.service.db.rootpassword }}
