apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.web.name }}-svc"
  labels:
    {{- include "web-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "web-db.selectorLabels" . | nindent 4 }}
