apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-swagger"
  labels:
    #{{- include "web.labels" . | nindent 4 }}
    app: "{{ .Release.Name }}-swagger"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      #{{- include "web.selectorLabels" . | nindent 6 }}
      app: "{{ .Release.Name }}-swagger"
  template:
    metadata:
      labels:
        #{{- include "web.selectorLabels" . | nindent 8 }}
        app: "{{ .Release.Name }}-swagger"
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: swaggereditor
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.web.image }}:{{ .Values.web.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: swaggereditor
              containerPort: 8080
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
