{{ if .Values.sonarqube.enabled -}}
{{ $timestamp := now | unixEpoch }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-sonarqube-runner-{{ .Values.git.commitID }}-{{ $timestamp }}"
spec:
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      name: "{{ .Release.Name }}-sonarqube-runner-{{ .Values.git.commitID }}-{{ $timestamp }}"
    spec:
      containers:
        - name: "sonarqube-scan-{{ .Values.git.commitID }}-{{ $timestamp }}"
          image: "{{ .Values.harbor.host }}/{{ .Values.harbor.cache }}/iiiorg/sonarqube-runner"
          command:
            - /bin/sh
            - -c
          args:
            - >-
              echo {{ .Values.git.repoName }} >> /opt/sonar-scanner/conf/sonar-project.properties;
              /usr/bin/before.sh;
              /usr/bin/entrypoint.sh sonar-scanner | /usr/bin/after.sh;
          env:
            # Sonarqube's URL
            - name: SONAR_HOST_URL
              valueFrom:
                secretKeyRef:
                  name: sonarqube
                  key: sonar-url
            # Auth token of sonarqube's bot
            - name: SONAR_LOGIN
              valueFrom:
                secretKeyRef:
                  name: sonar-bot
                  key: sonar-token
          volumeMounts:
            - mountPath: /usr/src
              name: initrepo
      # clone git repo and mount the code
      initContainers:
        - name: "clone-repo-{{ .Values.git.repoName }}-{{ .Values.git.branch }}-{{ .Values.git.commitID }}-{{ $timestamp }}"
          image: "{{ .Values.harbor.host }}/{{ .Values.harbor.cache }}/alpine/git"
          command: ['sh', '-c', 'cd /init-data; git clone --branch ${git_branch} http://root:${git_token}@${git_host}/root/${git_repo}.git .; rm -rf .git; ls; chmod -R 777 /init-data']
          env:
            - name: git_host
              valueFrom:
                secretKeyRef:
                  name: gitlab
                  key: git-host
            - name: git_repo
              value: {{ .Values.git.repoName }}
            - name: git_branch
              value: {{ .Values.git.branch }}
            - name: git_token
              valueFrom:
                secretKeyRef:
                  name: gitlab-bot
                  key: git-token
          volumeMounts:
            - mountPath: /init-data
              name: initrepo
      # 暫時專案資料儲存區
      volumes:
        - name: initrepo
          emptyDir: {}
      restartPolicy: Never
  backoffLimit: 4  
{{- end }}