apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Values.db.type }}-db"
  labels:
    #{{- include "db.labels" . | nindent 4 }}
    app: "{{ .Release.Name }}-{{ .Values.db.type }}-db"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      #{{- include "db.selectorLabels" . | nindent 6 }}
      app: "{{ .Release.Name }}-{{ .Values.db.type }}-db"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "db.selectorLabels" . | nindent 8 }}
        app: "{{ .Release.Name }}-{{ .Values.db.type }}-db"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "db.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.db.type }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          #image: "{{ .Values.db.image }}:{{ .Values.db.tag }}"
        {{- if eq .Values.db.type "mysql" }}
          image: "bitnami/mysql:{{ .Values.db.tag }}"
        {{- else if eq .Values.db.type "mariadb" }}
          image: "bitnami/mariadb:{{ .Values.db.tag }}"
        {{- else if eq .Values.db.type "postgresql" }}
          image: "bitnami/postgresql:{{ .Values.db.tag }}"
        {{- else if eq .Values.db.type "mongodb" }}
          image: "bitnami/mongodb:{{ .Values.db.tag }}"
        {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: db
            {{- if eq .Values.db.type "mysql" }}
              containerPort: 3306
            {{- else if eq .Values.db.type "mariadb" }}
              containerPort: 3306
            {{- else if eq .Values.db.type "postgresql" }}
              containerPort: 5432
            {{- else if eq .Values.db.type "mongodb" }}
              containerPort: 27017
            {{- end }}
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: httproot
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          env:
        {{- if eq .Values.db.type "mysql" }}
          - name: MYSQL_ROOT_USER
            value: {{ .Values.db.username }}
          - name: MYSQL_ROOT_PASSWORD
            value: {{ .Values.db.password }}
          - name: MYSQL_DATABASE
            value: {{ .Values.db.name }}
        {{- else if eq .Values.db.type "mariadb" }}
          - name: MARIADB_ROOT_USER
            value: {{ .Values.db.username }}
          - name: MARIADB_ROOT_PASSWORD
            value: {{ .Values.db.password }}
          - name: MARIADB_DATABASE
            value: {{ .Values.db.name }}
        {{- else if eq .Values.db.type "postgresql" }}
          - name: POSTGRESQL_USERNAME
            value: {{ .Values.db.username }}
          - name: POSTGRESQL_PASSWORD
            value: {{ .Values.db.password }}
          - name: POSTGRESQL_DATABASE
            value: {{ .Values.db.name }}
        {{- else if eq .Values.db.type "mongodb" }}
          - name: MONGODB_ROOT_PASSWORD
            value: {{ .Values.db.rootpassword }}
        {{- end }}
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: initdb
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      # 自動將資料庫所需匯入的表單匯入到資料庫
      initContainers:
        - name: initializing-a-new-instance
          image: alpine/git
          command: ['sh', '-c', 'git clone --branch ${git_branch} http://root:${git_token}@${git_host}/root/${git_repo}.git ; ls; mv -v ${git_repo}/db/* /initdb-data/; cd /initdb-data; ls; chmod -R 777 /initdb-data']
          env:
            - name: git_host
              value: {{ .Values.git.host }}
            - name: git_repo
              value: {{ .Values.git.repoName }}
            - name: git_branch
              value: {{ .Values.git.branch }}
            - name: git_token
              valueFrom:
                secretKeyRef:
                  name: gitlab-token
                  key: git-clone
          volumeMounts:
            - mountPath: /initdb-data
              name: initdb
      volumes:
        - name: initdb
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
