apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-{{ .Values.pipeline.sequence }}
  annotations:
    {{- include "iiidevops.annotations" . | nindent 4 }}
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-{{ .Values.pipeline.sequence }}
      annotations:
        {{- include "iiidevops.annotations" . | nindent 8 }}
    spec:
      containers:
        - name: webinspect-runner-{{ .Values.pipeline.sequence }}
          image: iiiorg/webinspect-runner:{{ .Values.webinspect.runnerVersion }}
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'cd /usr/src/app; node /usr/src/app/app.js;']
          env:
            - name: web_service_name
              value: {{ .Values.web.deployName }}-svc
            - name: project_name
              value: {{ .Values.git.repoName }}
            # Indicates the tested branch name
            - name: git_url
              value: {{ .Values.git.url }}
            - name: git_branch
              value: {{ include "numericSafe" .Values.git.branch | quote }}
            # Indicates the tested commit
            - name: git_commit_id
              value: {{ include "numericSafe" .Values.git.commitID | quote }}
            - name: verbose
              value: "true"
            - name: wi_base_url
              valueFrom:
                secretKeyRef:
                  name: webinspect
                  key: wi-base-url
            - name: api_origin
              valueFrom:
                secretKeyRef:
                  name: nexus
                  key: api-origin
            - name: api_username
              valueFrom:
                secretKeyRef:
                  name: nexus-bot
                  key: username
            - name: api_password
              valueFrom:
                secretKeyRef:
                  name: nexus-bot
                  key: password
      restartPolicy: Never
  backoffLimit: 2